apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nic-exporter
  namespace: {{ .Values.namespace }}
  labels:
    app: nic-exporter
rules:
- apiGroups:
  - extensions
  resources:
  - podsecuritypolicies
  resourceNames:
  - {{ .Values.name }}
  verbs:
  - "use"
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: nic-exporter
  namespace: {{ .Values.namespace }}
  labels:
    app: nic-exporter
subjects:
- kind: ServiceAccount
  name: nic-exporter
  namespace: {{ .Values.namespace }}
roleRef:
  kind: ClusterRole
  name: nic-exporter
  labels:
    app: nic-exporter
  apiGroup: rbac.authorization.k8s.io
